
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class CmdArgs : Luban.BeanBase
{
    internal CmdArgs(ByteBuf _buf) 
    {
        Type = (CmdType)_buf.ReadInt();
        {int __n0 = _buf.ReadSize(); Args = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); Args[__index0] = __e0;}}
    }

    internal static CmdArgs DeserializeCmdArgs(ByteBuf _buf)
    {
        return new CmdArgs(_buf);
    }

    public readonly CmdType Type;
    public readonly string[] Args;
   
    public const int __ID__ = -1746783977;
    public override int GetTypeId() => __ID__;

    internal  void ResolveRef(ConfigService tables)
    {
    }

    internal  void TranslateText(System.Func<string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "type:" + Type + ","
        + "args:" + Luban.StringUtil.CollectionToString(Args) + ","
        + "}";
    }
}

}

