
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config
{ 
    public enum CmdType
    {
        /// <summary>
        /// ui行为
        /// </summary>
        UI_RoleWiget = 80001,
        /// <summary>
        /// 打开某个UI
        /// </summary>
        UI_ShowUI = 80002,
        /// <summary>
        /// 打开弹窗Tips
        /// </summary>
        UI_Alert = 80003,
    }

} 

