
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
public sealed partial class color : Luban.BeanBase
{
    internal color(ByteBuf _buf) 
    {
        Value = _buf.ReadString();
    }

    internal static color Deserializecolor(ByteBuf _buf)
    {
        return new color(_buf);
    }

    public readonly string Value;
   
    public const int __ID__ = 94842723;
    public override int GetTypeId() => __ID__;

    internal  void ResolveRef(ConfigService tables)
    {
    }

    internal  void TranslateText(System.Func<string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "value:" + Value + ","
        + "}";
    }
}

}

