
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using AlicizaX;
using Cysharp.Threading.Tasks;

namespace Game.Config
{

    public interface IConfigBytesLoader
    {
        UniTask<ByteBuf> LoadCommonAsync(string file);

        UniTask<ByteBuf> LoadLocalizedAsync(string file);
    }

    public partial interface IConfigService : IService
    {
        public Tables.TbAudio TbAudio { get; }
        public Tables.Global Global { get; }
        /// <summary>
        /// 道具表
        /// </summary>
        public Tables.TbItem TbItem { get; }
        public Tables.Shop Shop { get; }

        UniTask Initialize(IConfigBytesLoader loader);
    }
     
    public partial class ConfigService : ServiceBase, IConfigService
    {
        private IConfigBytesLoader _loader;
        private bool _isLoaded;

        public Tables.TbAudio TbAudio { private set; get; }
        public Tables.Global Global { private set; get; }
        /// <summary>
        /// 道具表
        /// </summary>
        public Tables.TbItem TbItem { private set; get; }
        public Tables.Shop Shop { private set; get; }

        public async UniTask Initialize(IConfigBytesLoader loader)
        {
            _loader = loader ?? throw new ArgumentNullException(nameof(loader));
            if (_isLoaded)
            {
                await ReloadLocalizedAsync();
                return;
            }

            await LoadAsync();
        }

        private async UniTask LoadAsync()
        {
            EnsureLoader();

            if (_isLoaded)
            {
                return;
            }

            var loadTasks = new System.Collections.Generic.List<UniTask>();

            TbAudio = new Tables.TbAudio(() => _loader.LoadCommonAsync("tables_tbaudio"));
            loadTasks.Add(TbAudio.LoadAsync());
            Global = new Tables.Global(() => _loader.LoadCommonAsync("tables_global"));
            loadTasks.Add(Global.LoadAsync());
            TbItem = new Tables.TbItem(() => _loader.LoadCommonAsync("tables_tbitem"));
            loadTasks.Add(TbItem.LoadAsync());
            Shop = new Tables.Shop(() => _loader.LoadCommonAsync("tables_shop"));
            loadTasks.Add(Shop.LoadAsync());

            PostLoadAsync(ref loadTasks);

            await UniTask.WhenAll(loadTasks);

            ResolveRef();
            PostLocalizedTablesLoaded();
            _isLoaded = true;
            TranslateText();
        }

        private async UniTask ReloadLocalizedAsync()
        {
            EnsureLoader();

            if (!_isLoaded)
            {
                await LoadAsync();
                return;
            }

            var loadTasks = new System.Collections.Generic.List<UniTask>();

            PostReloadLocalizedAsync(ref loadTasks);

            await UniTask.WhenAll(loadTasks);

            PostLocalizedTablesLoaded();
            TranslateText();
        }

        private void ResolveRef()
        {
            TbAudio.ResolveRef(this);
            Global.ResolveRef(this);
            TbItem.ResolveRef(this);
            Shop.ResolveRef(this);
            PostResolveRef();
        }

        public void TranslateText()
        {
            if (!_isLoaded)
            {
                return;
            }

            string Translator(string key)
            {
                string value = key;
                PostTranslateText(key, ref value);
                return value;
            }
            TbAudio.TranslateText(Translator);
            Global.TranslateText(Translator);
            TbItem.TranslateText(Translator);
            Shop.TranslateText(Translator);
        }

        private void EnsureLoader()
        {
            if (_loader == null)
            {
                throw new InvalidOperationException("ConfigService is not initialized. Call Initialize(loader) first.");
            }
        }

        protected override void OnInitialize()
        {
        }

        protected override void OnDestroyService()
        {
        }

        partial void PostLoadAsync(ref System.Collections.Generic.List<UniTask> loadTasks);
        partial void PostReloadLocalizedAsync(ref System.Collections.Generic.List<UniTask> loadTasks);
        partial void PostLocalizedTablesLoaded();
        partial void PostResolveRef();
        partial void PostTranslateText(string key, ref string value);
    }
}

