
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config
{ 
    public enum EPartType
    {
        /// <summary>
        /// 手部
        /// </summary>
        Arm = 0,
        /// <summary>
        /// 胸部
        /// </summary>
        Chest = 1,
        /// <summary>
        /// 腿部
        /// </summary>
        Leg = 2,
        /// <summary>
        /// 腰部
        /// </summary>
        Waist = 3,
        /// <summary>
        /// 头部
        /// </summary>
        Head = 4,
        ALL = 5,
    }

} 

