
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config
{ 
    /// <summary>
    /// 商品类型
    /// </summary>
    public enum EShopCategory
    {
        /// <summary>
        /// 测试
        /// </summary>
        TEST = 1,
        /// <summary>
        /// 材料
        /// </summary>
        MATERIAL = 2,
        /// <summary>
        /// 装备
        /// </summary>
        EQUIPMENT = 3,
        /// <summary>
        /// 消耗品
        /// </summary>
        CONSUMABLE = 4,
    }

} 

