
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
/// <summary>
/// 取两个值的范围:<br/>1,3 就相当于[1,3)
/// </summary>
public sealed partial class RangeTowNumber : Luban.BeanBase
{
    internal RangeTowNumber(ByteBuf _buf) 
    {
        Range1 = _buf.ReadInt();
        Range2 = _buf.ReadInt();
    }

    internal static RangeTowNumber DeserializeRangeTowNumber(ByteBuf _buf)
    {
        return new RangeTowNumber(_buf);
    }

    /// <summary>
    /// 范围1
    /// </summary>
    public readonly int Range1;
    /// <summary>
    /// 范围2
    /// </summary>
    public readonly int Range2;
   
    public const int __ID__ = 601676584;
    public override int GetTypeId() => __ID__;

    internal  void ResolveRef(ConfigService tables)
    {
    }

    internal  void TranslateText(System.Func<string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "range1:" + Range1 + ","
        + "range2:" + Range2 + ","
        + "}";
    }
}

}

