
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
/// <summary>
/// 用于资源在游戏内的名字展示,以及资源在目录下的资产名称
/// </summary>
public sealed partial class ResourceCKBean : Luban.BeanBase
{
    internal ResourceCKBean(ByteBuf _buf) 
    {
        Content = _buf.ReadString();
        FileName = _buf.ReadString();
    }

    internal static ResourceCKBean DeserializeResourceCKBean(ByteBuf _buf)
    {
        return new ResourceCKBean(_buf);
    }

    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Content;
    /// <summary>
    /// 对应资源的文件名
    /// </summary>
    public readonly string FileName;
   
    public const int __ID__ = -1539577370;
    public override int GetTypeId() => __ID__;

    internal  void ResolveRef(ConfigService tables)
    {
    }

    internal  void TranslateText(System.Func<string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "content:" + Content + ","
        + "fileName:" + FileName + ","
        + "}";
    }
}

}

