
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config
{
/// <summary>
/// 用于保存中文原content以及对应的国际化Key
/// </summary>
public sealed partial class TranslateCKBean : Luban.BeanBase
{
    internal TranslateCKBean(ByteBuf _buf) 
    {
        Content = _buf.ReadString();
        Key = _buf.ReadString();
    }

    internal static TranslateCKBean DeserializeTranslateCKBean(ByteBuf _buf)
    {
        return new TranslateCKBean(_buf);
    }

    /// <summary>
    /// 内容
    /// </summary>
    public readonly string Content;
    /// <summary>
    /// 对应Key
    /// </summary>
    public readonly string Key;
   
    public const int __ID__ = 1171657446;
    public override int GetTypeId() => __ID__;

    internal  void ResolveRef(ConfigService tables)
    {
    }

    internal  void TranslateText(System.Func<string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "content:" + Content + ","
        + "key:" + Key + ","
        + "}";
    }
}

}

