
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Tables
{
public sealed partial class AudioConfig : Luban.BeanBase
{
    internal AudioConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Type = _buf.ReadInt();
        Path = _buf.ReadString();
        Loop = _buf.ReadBool();
        Volume = _buf.ReadInt();
    }

    internal static AudioConfig DeserializeAudioConfig(ByteBuf _buf)
    {
        return new Tables.AudioConfig(_buf);
    }

    /// <summary>
    /// 自增Id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 音频类型 0-Sound 1-UISound 2-Music 3-Voice 4-Ambient
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 音乐名称
    /// </summary>
    public readonly string Path;
    /// <summary>
    /// 循环
    /// </summary>
    public readonly bool Loop;
    /// <summary>
    /// 音量(0-100)
    /// </summary>
    public readonly int Volume;
   
    public const int __ID__ = 1478245551;
    public override int GetTypeId() => __ID__;

    internal  void ResolveRef(ConfigService tables)
    {
    }

    internal  void TranslateText(System.Func<string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "type:" + Type + ","
        + "path:" + Path + ","
        + "loop:" + Loop + ","
        + "volume:" + Volume + ","
        + "}";
    }
}

}

