
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Tables
{
public sealed partial class GlobalConfig : Luban.BeanBase
{
    internal GlobalConfig(ByteBuf _buf) 
    {
        Volume = _buf.ReadFloat();
        DefaultIcon = _buf.ReadString();
        {int n0 = _buf.ReadSize(); CommonColorTabs = new System.Collections.Generic.List<UnityEngine.Color>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { UnityEngine.Color _e0;  _e0 = ExternalTypeUtil.ParseColor(global::Game.Config.color.Deserializecolor(_buf)); CommonColorTabs.Add(_e0);}}
    }

    internal static GlobalConfig DeserializeGlobalConfig(ByteBuf _buf)
    {
        return new Tables.GlobalConfig(_buf);
    }

    /// <summary>
    /// 默认音量
    /// </summary>
    public readonly float Volume;
    /// <summary>
    /// 默认 Icon 位置
    /// </summary>
    public readonly string DefaultIcon;
    public readonly System.Collections.Generic.List<UnityEngine.Color> CommonColorTabs;
   
    public const int __ID__ = -1906359890;
    public override int GetTypeId() => __ID__;

    internal  void ResolveRef(ConfigService tables)
    {
    }

    internal  void TranslateText(System.Func<string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "volume:" + Volume + ","
        + "defaultIcon:" + DefaultIcon + ","
        + "commonColorTabs:" + Luban.StringUtil.CollectionToString(CommonColorTabs) + ","
        + "}";
    }
}

}

