
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Cysharp.Threading.Tasks;

namespace Game.Config.Tables
{
    public partial class Global
    {
        internal bool IsLoaded { get; private set; }
        internal bool IsResolved { get; private set; }


        private Tables.GlobalConfig _data;
        public Tables.GlobalConfig Data => _data;
        private readonly System.Func<UniTask<ByteBuf>> _loadFunc;

        public Global(System.Func<UniTask<ByteBuf>> loadFunc)
        {
            _loadFunc = loadFunc;
        }

        internal async UniTask LoadAsync()
        {
            ByteBuf _buf = await _loadFunc();
            int n = _buf.ReadSize();
            if (n != 1) throw new SerializationException("table mode=one, but size != 1");
            _data = global::Game.Config.Tables.GlobalConfig.DeserializeGlobalConfig(_buf);
            PostInit();
            IsLoaded = true;
        }

        /// <summary>
        /// 默认音量
        /// </summary>
        public float Volume => _data.Volume;
        /// <summary>
        /// 默认 Icon 位置
        /// </summary>
        public string DefaultIcon => _data.DefaultIcon;
        public System.Collections.Generic.List<UnityEngine.Color> CommonColorTabs => _data.CommonColorTabs;

        internal void ResolveRef(ConfigService tables)
        {
            _data.ResolveRef(tables);
            PostResolveRef();
            IsResolved = true;
        }

        internal void TranslateText(System.Func<string, string> translator)
        {
            _data.TranslateText(translator);
        }


        internal void Reset()
        {
            IsLoaded = false;
            IsResolved = false;
            _data = default;
        }

        partial void PostInit();
        partial void PostResolveRef();
    }
}

