
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Tables
{
public sealed partial class ItemConfig : Luban.BeanBase
{
    internal ItemConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        _NameKey = _buf.ReadString();
        _Name = _NameKey;
        Icon = _buf.ReadString();
        Type = (item.EItemType)_buf.ReadInt();
        Quality = (item.EQuality)_buf.ReadInt();
        Price = _buf.ReadInt();
        _DescKey = _buf.ReadString();
        _Desc = _DescKey;
        {int n0 = _buf.ReadSize(); Tags = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); Tags.Add(_e0);}}
    }

    internal static ItemConfig DeserializeItemConfig(ByteBuf _buf)
    {
        return new Tables.ItemConfig(_buf);
    }

    /// <summary>
    /// 道具ID
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    private readonly string _NameKey;
    private string _Name;
    public string Name => _Name;
    /// <summary>
    /// 图标
    /// </summary>
    public readonly string Icon;
    /// <summary>
    /// 道具类型
    /// </summary>
    public readonly item.EItemType Type;
    /// <summary>
    /// 道具品质
    /// </summary>
    public readonly item.EQuality Quality;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 描述
    /// </summary>
    private readonly string _DescKey;
    private string _Desc;
    public string Desc => _Desc;
    /// <summary>
    /// 标签
    /// </summary>
    public readonly System.Collections.Generic.List<string> Tags;
   
    public const int __ID__ = -1046574242;
    public override int GetTypeId() => __ID__;

    internal  void ResolveRef(ConfigService tables)
    {
    }

    internal  void TranslateText(System.Func<string, string> translator)
    {
        _Name = translator(_NameKey);
        _Desc = translator(_DescKey);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "type:" + Type + ","
        + "quality:" + Quality + ","
        + "price:" + Price + ","
        + "desc:" + Desc + ","
        + "tags:" + Luban.StringUtil.CollectionToString(Tags) + ","
        + "}";
    }
}

}

