
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace Game.Config.Tables
{
public sealed partial class ShopConfig : Luban.BeanBase
{
    internal ShopConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ItemId = _buf.ReadInt();
        ItemId_Ref = null;
        Type = (EShopCategory)_buf.ReadInt();
    }

    internal static ShopConfig DeserializeShopConfig(ByteBuf _buf)
    {
        return new Tables.ShopConfig(_buf);
    }

    /// <summary>
    /// 递增id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 道具表id
    /// </summary>
    public readonly int ItemId;
    public Tables.ItemConfig ItemId_Ref;
    /// <summary>
    /// 商店类型页签对应
    /// </summary>
    public readonly EShopCategory Type;
   
    public const int __ID__ = 113652993;
    public override int GetTypeId() => __ID__;

    internal  void ResolveRef(ConfigService tables)
    {
        ItemId_Ref = tables.TbItem.GetOrDefault(ItemId);
    }

    internal  void TranslateText(System.Func<string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "itemId:" + ItemId + ","
        + "type:" + Type + ","
        + "}";
    }
}

}

