
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Cysharp.Threading.Tasks;

namespace Game.Config.Tables
{
    /// <summary>
    /// 道具表
    /// </summary>
    public partial class TbItem
    {
        internal bool IsLoaded { get; private set; }
        internal bool IsResolved { get; private set; }

        private readonly System.Func<UniTask<ByteBuf>> _loadFunc;
        private readonly System.Collections.Generic.Dictionary<int, Tables.ItemConfig> _dataMap;
        private readonly System.Collections.Generic.List<Tables.ItemConfig> _dataList;
            
        public TbItem(System.Func<UniTask<ByteBuf>> loadFunc)
        {
            _dataMap = new System.Collections.Generic.Dictionary<int, Tables.ItemConfig>();
            _dataList = new System.Collections.Generic.List<Tables.ItemConfig>();
            
            _loadFunc = loadFunc;
        }

        internal async UniTask LoadAsync()
        {
            ByteBuf _buf = await _loadFunc();
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                Tables.ItemConfig _v;
                _v = global::Game.Config.Tables.ItemConfig.DeserializeItemConfig(_buf);
                _dataList.Add(_v);
                _dataMap.Add(_v.Id, _v);
            }
            PostInit();
            IsLoaded = true;
        }

        public System.Collections.Generic.Dictionary<int, Tables.ItemConfig> DataMap => _dataMap;
        public System.Collections.Generic.List<Tables.ItemConfig> DataList => _dataList;


        public Tables.ItemConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        public Tables.ItemConfig Get(int key) => _dataMap[key];
        public Tables.ItemConfig this[int key] => _dataMap[key];

        internal void ResolveRef(ConfigService tables)
        {
            foreach(var value in _dataList)
            {
                value.ResolveRef(tables);
            }
            PostResolveRef();
            IsResolved = true;
        }

        internal void TranslateText(System.Func<string, string> translator)
        {
            foreach(var value in _dataList)
            {
                value.TranslateText(translator);
            }
        }



        internal void Reset()
        {
            IsLoaded = false;
            IsResolved = false;
            _dataMap.Clear();
            _dataList.Clear();
        }

        partial void PostInit();
        partial void PostResolveRef();
    }
}

