using AlicizaX.UI;
using UnityEngine;
using UnityEngine.UI;
using AlicizaX.UI.Runtime;
namespace Game.UI
{
	[UIRes(ui_UIShopWindow.ResTag, EUIResLoadType.AssetBundle)]
	public partial class ui_UIShopWindow : UIHolderObjectBase
	{
		public const string ResTag = "UIShopWindow";
		#region Generated by Script Tool

		[SerializeField]
		private UXButton mBtnClose;
		public UXButton BtnClose => mBtnClose;

		[SerializeField]
		private Image mImgBackGround;
		public Image ImgBackGround => mImgBackGround;

		[SerializeField]
		private Image mImgHeaderPanel;
		public Image ImgHeaderPanel => mImgHeaderPanel;

		[SerializeField]
		private Image mImgListPanel;
		public Image ImgListPanel => mImgListPanel;

		[SerializeField]
		private Image mImgTabPanel;
		public Image ImgTabPanel => mImgTabPanel;

		[SerializeField]
		private RecyclerView mScrollViewGoodsLinerList;
		public RecyclerView ScrollViewGoodsLinerList => mScrollViewGoodsLinerList;

		[SerializeField]
		private RecyclerView mScrollViewGoodsList;
		public RecyclerView ScrollViewGoodsList => mScrollViewGoodsList;

		[SerializeField]
		private RecyclerView mScrollViewGoodsLoopList;
		public RecyclerView ScrollViewGoodsLoopList => mScrollViewGoodsLoopList;

		[SerializeField]
		private UXTextMeshPro mTextCurrency;
		public UXTextMeshPro TextCurrency => mTextCurrency;

		[SerializeField]
		private UXTextMeshPro mTextSubTitle;
		public UXTextMeshPro TextSubTitle => mTextSubTitle;

		[SerializeField]
		private UXTextMeshPro mTextTitle;
		public UXTextMeshPro TextTitle => mTextTitle;

		[SerializeField]
		private UXToggle mTogItem;
		public UXToggle TogItem => mTogItem;

		[SerializeField]
		private UXToggle mTogPack;
		public UXToggle TogPack => mTogPack;

		[SerializeField]
		private UXToggle mTogRecommend;
		public UXToggle TogRecommend => mTogRecommend;

		[SerializeField]
		private UXToggle mTogSkin;
		public UXToggle TogSkin => mTogSkin;

		#endregion


	}
}
