
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Game.Config.item
{ 
    /// <summary>
    /// 道具类型
    /// </summary>
    public enum EItemType
    {
        /// <summary>
        /// 使用后消耗的道具
        /// </summary>
        CONSUMABLE = 1,
        /// <summary>
        /// 合成或升级材料
        /// </summary>
        MATERIAL = 2,
        /// <summary>
        /// 可装备道具
        /// </summary>
        EQUIPMENT = 3,
        /// <summary>
        /// 货币或兑换道具
        /// </summary>
        CURRENCY = 4,
        /// <summary>
        /// 任务相关道具
        /// </summary>
        QUEST = 5,
        /// <summary>
        /// 其他类型道具
        /// </summary>
        OTHER = 6,
    }

} 

